export { Composer, type BarSnapshot } from './composer.ts'
export { ARRANGEMENTS, type Arrangement } from './arrangement.ts'
export type { PlayerId, RoleId, Seat } from './context.ts'
export type { MelodyInfo } from './melody.ts'
export { DEFAULT_PARAMS, PARAM_DEFS, type BgmParams, type ParamDef } from './params.ts'
export { PLAYER_DEFS, ROLE_DEFS, type PlayerDef, type RoleDef } from './parts.ts'
export { Key, SCALES, pitchName, type ScaleDef } from './scales.ts'
